//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectGameInterface
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stats()
        {
            this.Wins = 0;
            this.Draws = 0;
            this.Losses = 0;
        }
    
        public int Id { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Draws { get; set; }
        public Nullable<int> Losses { get; set; }
        public int PlayerId { get; set; }
        public int GameId { get; set; }
        public Nullable<int> LastScore { get; set; }
        public Nullable<System.DateTime> LastGame { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Game Game { get; set; }
    }
}
